sudo: enabled
language: rust
cache: cargo

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_install:
 - sudo apt install libasound2-dev libsdl2-dev pkg-config

before_script:
 - rustup component add rustfmt-preview
script:
 - cargo fmt --all -- --write-mode=diff
 - cargo build
 - cargo test
