sudo: enabled
language: rust
cache: cargo

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_install:
 - sudo add-apt-repository -y ppa:team-xbmc/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -y  libsdl2-dev

before_script:
 - rustup component add rustfmt-preview
script:
 - cargo fmt --all -- --write-mode=diff
 - cargo build
 - cargo test
