[package]
name = "hexadventure"
version = "0.1.0"
authors = ["as-f <as-f@users.noreply.github.com>"]

[[bin]]
name = "hexadventure_gui"
path = "src/main.rs"
required-features = ["gui"]

[dependencies]
rand = "0.4"
ggez = {version = "0.4", optional = true }

[features]
gui = ["ggez"]
