[package]
name = "hexadventure_gui"
version = "0.1.0"
authors = ["as-f <as-f@users.noreply.github.com>"]

[dependencies]
hexadventure = { version = "0.1", path = "../hexadventure" }
ggez = "0.4"
image = "0.18"
